### ISSUE TITLE
What is the Flaky Projects Thesis about

### ISSUE THREAD

**Issue by sylhare** [Titanflex/bachelorThesisFlakyProjects#1]
Hi,

I found this repo and I was wondering what is it about, I found my name in one of the `.csv` so I was getting curious.

Let me know :)

**Comment by Titanflex** [comment]
Hi,

Sadly my bachelor thesis is completely written in german, but I try to summarize it for you :-)
Basically I researched flaky tests in python, in particular:
1. Occurrences of flaky tests in a number of open source python projects (that probably explains your name in the .csv files)
2. How to categorize the flaky tests which have been found
3. How often and how is the flaky library for python used
4. Is there a correlation between flakiness of a test and the number of test authors

I hope this explains the occurence of your name in some of these files.
Thanks for asking and being curious about my bachelor thesis!

**Comment by sylhare** [comment]
Oh I see thanks, that's cool :)
